
const Head = () => {
    return (
        <>
            <title>SQL Ninja</title>
            <meta name="description" content="Generated by sandro 2023" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </>
    )
}


export default Head;